### ISSUE TITLE
Can't easily parse XML with link added at the end of file outside XML

### ISSUE THREAD

**Issue by ccarpo** [JGoutin/movie_nfo_generator#3]
Hi, 

I can't really parse the XML easily without removing the link at the end of the file. 
Could we have an option to disable the link generation or include it inside the XML as a "source_info" parameter or something like that?

Greets CCarpo

**Comment by JGoutin** [comment]
Hello,

In fact, the generated file follows this format: [KODI NFO Combination file](https://kodi.wiki/view/NFO_files/Combination)

But, an option may be added to generate raw XML metadata instead.

**Comment by ccarpo** [comment]
Sorry. I just sow now that this is spcifially for Kodi. Nevermind I forked and made my own adjustments... Thanks for responding
